apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: example
spec:
  containers:
  - name: example-container
    image: ubuntu:latest
    command: ['sh', '-c', 'echo $(EXAMPLE_VARIABLE1) $(EXAMPLE_VARIABLE2)']
