apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

configMapGenerator:
# Generate config map: name = configmap-foo-<random string>
- name: configmap-foo
  files:
  - config1.txt
# Generate config map: name = configmap-bar-<random string>
- name: configmap-bar
  files:
  - config2.txt
