apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pod1.yaml
- pod2.yaml
images:
# Added by `kustomize edit set image ubuntu=example/ubuntu:18.04`
- name: ubuntu
  newName: example/ubuntu
  newTag: "18.04"
# Added by `kustomize edit set image ubuntu-debug=example/ubuntu-debug:18.04`
- name: ubuntu-debug
  newName: example/ubuntu-debug
  newTag: "18.04"
