apiVersion: v1
kind: Pod
metadata:
  name: example-pod1
  labels:
    app: example
spec:
  containers:
  - name: example-container
    image: ubuntu:latest
    command: ['sh', '-c', 'sleep 3600']
  - name: example-container2
    image: ubuntu-debug:latest
    command: ['sh', '-c', 'sleep 3600']
