apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
# Added by `kustomize edit set namespace example-foo-`
namePrefix: example-foo-
# Variables
vars:
  - name: EXAMPLE_VARIABLE1
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: deployment1
      # default is metadata.name
  # - name: EXAMPLE_VARIABLE2
  #   objref:
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     name: deployment1
  #   fieldref:
  #     # https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/varreference.go
  #     fieldpath: spec/template/spec/containers/command
